version: "3"

services:
  html-container:
    build:
      context: ./html-container
    ports:
      - "80:80"
    networks:
      - app-network

  html-css-test:
    build:
      context: ./html-css-test-app
    ports:
      - "3001:3001"
    networks:
      - app-network

  javascript-test:
    build:
      context: ./javascript-test-app
    ports:
      - "3002:3002"
    networks:
      - app-network

  kakao-authentication:
    build:
      context: ./kakao-authentication
    ports:
      - "3004:3004"
    networks:
      - app-network

  navigation-bar:
    build:
      context: ./navigation-bar-app
    ports:
      - "3005:3005"
    networks:
      - app-network

  react-test-app:
    build:
      context: ./react-test-app
    ports:
      - "3006:3006"
    networks:
      - app-network

  practice-app:
    build:
      context: ./practice-app
    ports:
      - "3007:3007"
    networks:
      - app-network

  google-authentication:
    build:
      context: ./google-authentication
    ports:
      - "3100:3100"
    networks:
      - app-network

  recoil-board-app:
    build:
      context: ./recoil-board-app
    ports:
      - "3101:3101"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge