# ????? Eureka ?? ?? Discovery ???? ????.
# ? ??? ???? ????? ?? ???.
# Gateway? ??? ?? ???? ???? ??? ????.
# ? ?? ??? IP? port? ??? ????? ??? ?? ??? ? ?? ???.
# ? ??? ??? Spring Cloud Netflix Eureka Server ?? ???.
spring:
  application:
    name: discovery

# ?? ??? 9876?
server:
  port: 9876

# Eureka ?? ??? ????? localhost? ?????.
# Discovery?? ??? Replication(?? ??) ?? ?? ???.
# ?? ?????? Replication? ??? ??? ?????
# (100?? ??? ????? ???? ?? ???? ?? ??? ??? ??? ??)
# ??? ??? ?? ??? (?? ?? ??)
# ?? ? ??? Replication X
eureka:
  instance:
    hostname: localhost
  # register-with-eureka ? fetch-registry ???
  # Eureka? Discovery ??? ???? Client? ???? ?? ??? ?????.
  # register-with-eureka: false?
  # ? ?? ??? Eureka ??? ???? ??
  # ? ??????? Eureka ?? ??? ?? ?? Eureka ??? ???? ??.
  # fetch-registry: false?
  # ? ??? ?? Eureka ???? Service Registry? ???? ??? ?????.
  # Service Registry(??? ?????)? ??
  # ?? ???, ??, ?? ?? ?? ?? ?????
  # ??? ??? ?? 3??? Service Registry? ???? ???.
  # ?? Replication? ?? ???? ?? ?? ?? ??? ?? ??? ??? ??? ???.
  # ??? ? ???? ?? ?? ?? ??? ?? (??, ?? ??)? ???? ??? ?
  # ??? ??? ? ??? ?? ? ??? ???? ??? ?????.
  # ????? ?? ? ?? ?? ??? ? ?? ??? ??? ?? ??? ? ??

  # 1. Discovery ??? ???? ???.
  # 2. Replication? ?? ?? ?? ??? ???? ??.
  # 3. ?? ?? ??? ??? ?? ?? ???? ??.
  client:
    register-with-eureka: false
    fetch-registry: false
    # Eureka Client ?? Eureka Server? ?? ? ??? ?? ??? ???? ?????.
    # ? ????? ??? Eureka Client? ???, ??, ?? ???
    # Client?? ??? ?? ? ? defaultZone? ?? ???? ???? ?
    # ?? ?????? ??? ???? ??? ?????? ???? ???.
    service-url:
      defaultZone: http://localhost:9876/eureka/
    # Eureka Server? ?? ?? ??? ???? ?????.
    # enable-self-preservation <- ???? ? ??? ???? ???.
    # ????? true? ????? ? ??? ?? ???
    # ??? ???? ???? ??? ???? ?
    # ?? ???? ??? ??? ???? ? ? ????.
    # ? ???? Eureka? ???? ????? ?? ???
    # ?? ????? ? ?? true? ???? ??? ????
    # ?? ? ???? DDoS ??? ??? ? ? ????.
    server:
      enable-self-preservation: false
    # Eureka ???? ?? ?????.
    # ????? ?? ???? ??? ?? ?? ???? ???? ????? ???? ???.
    # ?? MSA? ????? ??? 100????? ??? ???? ???? ?? ?????.
    # ?? ?? 1?? 1000?? ????? 1000?? ???? ???? ??? ???.
    # ??? `peer-eureka-nodes` ??? ??
    # Eureka Server?? ?? ??? ? ??? ????.
    # ???? ?? 1?? ???? ??? ?? ??? ???? ?? ?????.
    # Replication ??? ??? ??? ??? ?? ???? ?? ??????
    # ?? ?????? ??? ???? ??? ? ??? ??? ??? ????.
    cluster:
      peer-eureka-nodes: http://localhost:9876/eureka/