spring:
  application:
    name: simple

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9876/eureka

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true
  jackson:
    enabled: true

logging:
  level:
    org.example.simple.client: DEBUG
    feign: DEBUG