server:
  port: 12345

spring:
  application:
    name: simple

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9876/eureka

feign:
  hystrix:
    enabled: false